In [1]:
import numpy as np
import sys

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
print(a)

[1 2 3 4]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# get the dimensions
a.ndim

1

In [7]:
# get shape
a.shape

(4,)

In [8]:
b.shape

(2, 3)

In [9]:
# get type
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('float64')

In [11]:
#get size in bytes
a.itemsize
a.size

4

In [12]:
b.itemsize

8

In [13]:
#get total size in bytes
a.size * a.itemsize

16

In [14]:
b.size * b.itemsize

48

In [15]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [16]:
np.copy?

In [ ]:
d