In [1]:
# import numpy as np

In [2]:
# array1=np.array([[3,2,4],[4,5,8]])

In [3]:
# print(array1)

In [4]:
# array1.shape

In [5]:
# array1.dtype

In [6]:
# np.zeros((4,6))

In [7]:
# np.ones(6)

In [8]:
# np.empty((4,6))

In [9]:
# array1

In [10]:
# array1**array1

In [11]:
# 1/array1

## Slicing

In [12]:
# array2=np.array([5,4,3,45,64,34])

In [13]:
# arr=array2[4:6].copy()

In [14]:
# arr

In [15]:
# arr[0]=9

In [16]:
# arr

In [17]:
# array2

In [18]:
# array1

In [19]:
# array1[0,2]

## More on numpy

In [20]:
# import numpy as np

In [21]:
# a=np.array([[1,2,3],
#              [4,5,6]])

In [22]:
# ar1.sum(axis=0)

In [23]:
# b=np.array([[7,8,9],
#             [2,8,0]])

In [24]:
# np.dot(a,b.transpose())

In [25]:
# np.cross(a,b)

## sorting

In [26]:
# a=np.array([[4,3,2],
#              [5,4,6]])

In [27]:
# np.sort(a,axis=0,kind='mergesort')    #sort using mergesort algo

## More numpy functions

In [28]:
import numpy as np

In [29]:
a=np.arange(6)

In [30]:
a

array([0, 1, 2, 3, 4, 5])

In [31]:
b=np.array([5,4,5,6,4,0,4,3,5,6,33,8])
b=b.reshape(4,3)

In [32]:
b

array([[ 5,  4,  5],
       [ 6,  4,  0],
       [ 4,  3,  5],
       [ 6, 33,  8]])

In [33]:
np.argsort(b,axis=0)     #shows the position of elements to sort

array([[2, 2, 1],
       [0, 0, 0],
       [1, 1, 2],
       [3, 3, 3]], dtype=int64)

In [37]:
np.argmin(b)

5

In [35]:
np.argmax(b)

10